name: spark
channels:
  - conda-forge
  - defaults
dependencies:
  - _ipython_minor_entry_point=8.7.0=hb6b4a82_0
  - abseil-cpp=20211102.0=hd638f34_2
  - aiohttp=3.8.3=py310h90acd4f_1
  - aiosignal=1.3.1=pyhd8ed1ab_0
  - airflow=2.5.0=py310h795411f_0
  - alembic=1.9.1=pyhd8ed1ab_0
  - anyio=3.6.2=pyhd8ed1ab_0
  - apache-airflow-providers-common-sql=1.3.3=pyhd8ed1ab_0
  - apache-airflow-providers-ftp=3.3.0=pyhd8ed1ab_0
  - apache-airflow-providers-http=4.1.1=pyhd8ed1ab_0
  - apache-airflow-providers-imap=3.1.1=pyhd8ed1ab_0
  - apache-airflow-providers-sqlite=3.3.1=pyhd8ed1ab_0
  - apispec=3.3.2=py_0
  - appnope=0.1.2=py310h2ec42d9_3
  - argcomplete=1.12.3=pyhd8ed1ab_0
  - argon2-cffi=21.3.0=pyhd8ed1ab_0
  - argon2-cffi-bindings=21.2.0=py310h90acd4f_3
  - arrow=1.2.3=pyhd8ed1ab_0
  - arrow-cpp=8.0.0=py310h72c8010_0
  - asttokens=2.0.5=pyhd8ed1ab_0
  - async-timeout=4.0.2=pyhd8ed1ab_0
  - atk-1.0=2.36.0=haf1e3a3_2
  - attrs=22.2.0=pyh71513ae_0
  - aws-c-common=0.4.57=hb1e8313_1
  - aws-c-event-stream=0.1.6=h27ab107_3
  - aws-checksums=0.1.9=hd78c526_0
  - aws-sdk-cpp=1.8.185=he271ece_0
  - babel=2.11.0=pyhd8ed1ab_0
  - backcall=0.2.0=pyh9f0ad1d_0
  - backports=1.0=pyhd8ed1ab_3
  - backports.functools_lru_cache=1.6.4=pyhd8ed1ab_0
  - bcrypt=3.2.2=py310h90acd4f_1
  - beautifulsoup4=4.11.1=pyha770c72_0
  - bleach=4.1.0=pyhd8ed1ab_0
  - blinker=1.5=pyhd8ed1ab_0
  - boost-cpp=1.73.0=hca72f7f_12
  - brotli=1.0.9=hb7f2c08_8
  - brotli-bin=1.0.9=hb7f2c08_8
  - brotlipy=0.7.0=py310h90acd4f_1005
  - bzip2=1.0.8=h0d85af4_4
  - c-ares=1.18.1=h0d85af4_0
  - ca-certificates=2023.01.10=hecd8cb5_0
  - cachelib=0.9.0=pyhd8ed1ab_0
  - cachetools=5.2.1=pyhd8ed1ab_0
  - cairo=1.16.0=h0ab9d94_1001
  - cattrs=22.2.0=pyhd8ed1ab_0
  - certifi=2022.12.7=pyhd8ed1ab_0
  - cffi=1.15.1=py310hc55c11b_0
  - charset-normalizer=2.1.1=pyhd8ed1ab_0
  - click=8.1.3=unix_pyhd8ed1ab_2
  - clickclick=1.2.2=py_1
  - colorama=0.4.6=pyhd8ed1ab_0
  - colorlog=4.8.0=py310h2ec42d9_2
  - colour=0.1.5=py_0
  - comm=0.1.2=pyhd8ed1ab_0
  - commonmark=0.9.1=py_0
  - configupdater=3.1.1=pyhd8ed1ab_0
  - connexion=2.14.1=pyhd8ed1ab_0
  - cron-descriptor=1.2.24=pyhd8ed1ab_0
  - croniter=1.3.8=pyhd8ed1ab_0
  - cryptography=39.0.0=py310h23bb4e6_0
  - cyrus-sasl=2.1.27=ha724b88_5
  - dataclasses=0.8=pyhc8e2a94_3
  - debugpy=1.5.1=py310h9d931ec_1
  - decorator=5.1.1=pyhd8ed1ab_0
  - defusedxml=0.7.1=pyhd8ed1ab_0
  - deprecated=1.2.13=pyh6c4a22f_0
  - dill=0.3.6=pyhd8ed1ab_1
  - dnspython=2.3.0=pyhd8ed1ab_0
  - docutils=0.19=py310h2ec42d9_1
  - email-validator=1.3.0=pyhd8ed1ab_0
  - email_validator=1.3.0=hd8ed1ab_0
  - entrypoints=0.4=pyhd8ed1ab_0
  - exceptiongroup=1.1.0=pyhd8ed1ab_0
  - executing=0.8.3=pyhd8ed1ab_0
  - flask=2.2.2=pyhd8ed1ab_0
  - flask-appbuilder=4.1.4=pyhd8ed1ab_0
  - flask-babel=2.0.0=pyh9f0ad1d_0
  - flask-caching=2.0.2=pyhd8ed1ab_0
  - flask-jwt-extended=4.4.4=pyhd8ed1ab_0
  - flask-login=0.6.2=pyhd8ed1ab_0
  - flask-session=0.4.0=pyhd8ed1ab_0
  - flask-sqlalchemy=2.5.1=pyhd8ed1ab_0
  - flask-wtf=1.1.1=pyhd8ed1ab_0
  - flit-core=3.8.0=pyhd8ed1ab_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=hab24e00_0
  - fontconfig=2.13.94=h10f422b_0
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - freetype=2.10.4=h3f81eb7_2
  - fribidi=1.0.10=hbcb3906_0
  - frozenlist=1.3.3=py310h90acd4f_0
  - furl=2.1.3=pyhd8ed1ab_0
  - future=0.18.3=pyhd8ed1ab_0
  - gdk-pixbuf=2.42.8=h6c40b1e_2
  - gettext=0.21.0=h7535e17_0
  - gflags=2.2.2=hb1e8313_1004
  - giflib=5.2.1=hb7f2c08_3
  - glib=2.69.1=h8346a28_1
  - glog=0.6.0=h8ac2a54_0
  - gobject-introspection=1.72.0=py310h4d44cf5_0
  - google-api-core=2.10.1=pyhd8ed1ab_0
  - google-auth=2.16.0=pyh1a96a4e_1
  - google-cloud-core=2.3.2=pyhd8ed1ab_0
  - google-cloud-sdk=413.0.0=py310h2ec42d9_0
  - google-cloud-storage=2.7.0=pyh1a96a4e_0
  - google-crc32c=1.1.2=py310h6f7428f_4
  - google-resumable-media=2.4.0=pyhd8ed1ab_0
  - googleapis-common-protos=1.57.0=py310h2ec42d9_0
  - graphite2=1.3.14=he9d5cce_1
  - graphviz=2.42.3=h055b950_2
  - greenlet=2.0.1=py310h7a76584_0
  - grpc-cpp=1.46.1=h067a048_0
  - grpcio=1.42.0=py310haaead3b_0
  - gst-plugins-base=1.14.0=h4180768_2
  - gstreamer=1.14.0=h0fc69c2_2
  - gtk2=2.24.33=h4d89f74_2
  - gts=0.7.6=h2684ab5_0
  - gunicorn=20.1.0=py310h2ec42d9_3
  - h11=0.14.0=pyhd8ed1ab_0
  - h2=4.1.0=pyhd8ed1ab_0
  - harfbuzz=4.3.0=hffc734d_1
  - hpack=4.0.0=pyh9f0ad1d_0
  - httpcore=0.16.3=pyhd8ed1ab_0
  - httpx=0.23.3=pyhd8ed1ab_0
  - hyperframe=6.0.1=pyhd8ed1ab_0
  - icu=58.2=h0a44026_1000
  - idna=3.4=pyhd8ed1ab_0
  - importlib-metadata=6.0.0=pyha770c72_0
  - importlib_resources=5.10.2=pyhd8ed1ab_0
  - infinity=1.5=pyhd8ed1ab_0
  - inflection=0.5.1=pyh9f0ad1d_0
  - iniconfig=1.1.1=pyh9f0ad1d_0
  - intervals=0.9.2=pyhd8ed1ab_0
  - ipykernel=6.19.2=pyh736e0ef_0
  - ipython=8.7.0=pyhd1c38e8_0
  - ipython_genutils=0.2.0=py_1
  - ipywidgets=7.6.5=pyhd8ed1ab_0
  - itsdangerous=2.1.2=pyhd8ed1ab_0
  - jedi=0.18.1=pyhd8ed1ab_2
  - jinja2=3.1.2=pyhd8ed1ab_1
  - jpeg=9e=hb7f2c08_3
  - json5=0.9.6=pyhd3eb1b0_0
  - jsonschema=4.17.3=pyhd8ed1ab_0
  - jupyter=1.0.0=py310h2ec42d9_8
  - jupyter_client=7.4.8=pyhd8ed1ab_0
  - jupyter_console=6.4.4=pyhd8ed1ab_0
  - jupyter_core=5.1.1=py310h2ec42d9_0
  - jupyter_server=1.23.4=py310hecd8cb5_0
  - jupyterlab=3.5.2=pyhd8ed1ab_0
  - jupyterlab_pygments=0.1.2=pyh9f0ad1d_0
  - jupyterlab_server=2.16.5=pyhd8ed1ab_0
  - jupyterlab_widgets=1.0.0=pyhd8ed1ab_1
  - krb5=1.19.3=hb49756b_0
  - lazy-object-proxy=1.9.0=py310h90acd4f_0
  - libabseil=20211102.0=cxx17_hd8326b1_2
  - libblas=3.9.0=16_osx64_openblas
  - libboost=1.73.0=h3fa6bed_12
  - libbrotlicommon=1.0.9=hb7f2c08_8
  - libbrotlidec=1.0.9=hb7f2c08_8
  - libbrotlienc=1.0.9=hb7f2c08_8
  - libcblas=3.9.0=16_osx64_openblas
  - libclang=12.0.0=default_he082bbe_2
  - libcrc32c=1.1.2=he49afe7_0
  - libcurl=7.79.1=hf45b732_1
  - libcxx=14.0.6=hccf4f1f_0
  - libedit=3.1.20191231=h0678c8f_2
  - libev=4.33=haf1e3a3_1
  - libevent=2.1.10=h815e4d9_4
  - libffi=3.3=h046ec9c_2
  - libgfortran=5.0.0=11_3_0_h97931a8_31
  - libgfortran5=11.3.0=h082f757_31
  - libiconv=1.16=haf1e3a3_0
  - liblapack=3.9.0=16_osx64_openblas
  - libllvm12=12.0.0=hd011deb_1
  - libnghttp2=1.43.0=h6f36284_1
  - libntlm=1.6=h9ed2024_0
  - libopenblas=0.3.21=openmp_h429af6e_3
  - libpcap=1.9.1=h0b31af3_2
  - libpng=1.6.37=h5481273_4
  - libpq=12.9=h1c9f633_3
  - libprotobuf=3.20.1=hbc0c0cd_4
  - libsodium=1.0.18=hbcb3906_1
  - libssh2=1.10.0=h7535e13_3
  - libthrift=0.15.0=hab56fdc_1
  - libtiff=4.2.0=h1167814_3
  - libwebp=1.2.4=hf6ce154_1
  - libwebp-base=1.2.4=h775f41a_0
  - libxml2=2.9.14=hbf8cd5e_0
  - libxslt=1.1.35=h5b33f42_0
  - libzlib=1.2.13=h8a1eda9_5
  - linkify-it-py=2.0.0=pyhd8ed1ab_0
  - llvm-openmp=15.0.7=h61d9ccf_0
  - lockfile=0.12.2=py_1
  - lxml=4.9.1=py310h6c45266_0
  - lz4-c=1.9.3=he49afe7_1
  - mako=1.2.4=pyhd8ed1ab_0
  - markdown=3.4.1=pyhd8ed1ab_0
  - markdown-it-py=2.1.0=pyhd8ed1ab_0
  - markupsafe=2.1.2=py310h90acd4f_0
  - marshmallow=3.19.0=pyhd8ed1ab_0
  - marshmallow-enum=1.5.1=pyh9f0ad1d_3
  - marshmallow-oneofschema=3.0.1=pyhd8ed1ab_0
  - marshmallow-sqlalchemy=0.26.1=pyhd8ed1ab_0
  - matplotlib-inline=0.1.6=pyhd8ed1ab_0
  - mdit-py-plugins=0.3.3=pyhd8ed1ab_0
  - mdurl=0.1.0=pyhd8ed1ab_0
  - mistune=0.8.4=pyh1a96a4e_1006
  - mongo-tools=4.0.4=h81701ea_1000
  - mongodb=4.0.3=hccea1a4_0
  - multidict=6.0.4=py310h90acd4f_0
  - nbclassic=0.4.8=pyhd8ed1ab_0
  - nbclient=0.5.13=pyhd8ed1ab_0
  - nbconvert=6.5.4=py310hecd8cb5_0
  - nbformat=5.7.0=pyhd8ed1ab_0
  - ncurses=6.3=h96cf925_1
  - nest-asyncio=1.5.6=pyhd8ed1ab_0
  - notebook=6.5.2=pyha770c72_0
  - notebook-shim=0.2.2=pyhd8ed1ab_0
  - nspr=4.33=he9d5cce_0
  - nss=3.74=h31e2bf1_0
  - numpy=1.24.1=py310h788a5b3_0
  - openjdk=11.0.13=h8346a28_0
  - openssl=1.1.1s=hfd90126_1
  - orc=1.7.4=h4856350_1
  - orderedmultidict=1.0.1=py_0
  - packaging=23.0=pyhd8ed1ab_0
  - pandas=1.5.3=py310hecf8f37_1
  - pandocfilters=1.5.0=pyhd8ed1ab_0
  - pango=1.50.7=h80fe9ab_0
  - parso=0.8.3=pyhd8ed1ab_0
  - passlib=1.7.4=pyh9f0ad1d_0
  - pathspec=0.9.0=pyhd8ed1ab_0
  - pcre=8.45=he49afe7_0
  - pendulum=2.1.2=py310h90acd4f_5
  - pexpect=4.8.0=pyh1a96a4e_2
  - phonenumbers=8.13.4=pyhd8ed1ab_0
  - pickleshare=0.7.5=py_1003
  - pip=22.3.1=pyhd8ed1ab_0
  - pixman=0.38.0=h01d97ff_1003
  - pkgutil-resolve-name=1.3.10=pyhd8ed1ab_0
  - platformdirs=2.5.2=pyhd8ed1ab_1
  - pluggy=1.0.0=pyhd8ed1ab_5
  - ply=3.11=py_1
  - prison=0.2.1=pyhd8ed1ab_0
  - prometheus_client=0.14.1=pyhd8ed1ab_0
  - prompt-toolkit=3.0.36=pyha770c72_0
  - prompt_toolkit=3.0.36=hd8ed1ab_0
  - protobuf=3.20.1=py310hd4537e4_0
  - psutil=5.9.4=py310h90acd4f_0
  - ptyprocess=0.7.0=pyhd3deb0d_0
  - pure_eval=0.2.2=pyhd8ed1ab_0
  - py=1.11.0=pyh6c4a22f_0
  - pyarrow=8.0.0=py310h53e4f6e_0
  - pyasn1=0.4.8=py_0
  - pyasn1-modules=0.2.7=py_0
  - pycodestyle=2.10.0=pyhd8ed1ab_0
  - pycparser=2.21=pyhd8ed1ab_0
  - pygments=2.14.0=pyhd8ed1ab_0
  - pyjwt=2.6.0=pyhd8ed1ab_0
  - pyopenssl=23.0.0=pyhd8ed1ab_0
  - pyqt=5.15.7=py310he9d5cce_0
  - pyrsistent=0.19.3=py310h90acd4f_0
  - pysocks=1.7.1=pyha2e5f31_6
  - pytest=7.1.2=py310h2ec42d9_0
  - python=3.10.0=hdfd78df_5
  - python-daemon=2.3.2=pyhd8ed1ab_0
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python-fastjsonschema=2.16.2=pyhd8ed1ab_0
  - python-graphviz=0.16=pyhd3deb0d_1
  - python-nvd3=0.15.0=pyh9f0ad1d_2
  - python-slugify=7.0.0=pyhd8ed1ab_0
  - python_abi=3.10=2_cp310
  - pytz=2022.7.1=pyhd8ed1ab_0
  - pytzdata=2020.1=pyh9f0ad1d_0
  - pyu2f=0.1.5=pyhd8ed1ab_0
  - pyyaml=6.0=py310h90acd4f_5
  - pyzmq=23.2.0=py310h85fb675_0
  - qt-main=5.15.2=h719ae48_7
  - qt-webengine=5.15.9=h90a370e_4
  - qtconsole=5.4.0=pyhd8ed1ab_0
  - qtconsole-base=5.4.0=pyha770c72_0
  - qtpy=2.2.0=pyhd8ed1ab_0
  - qtwebkit=5.212=h24dc246_4
  - re2=2022.04.01=h96cf925_0
  - readline=8.2=h9e318b2_1
  - requests=2.28.2=pyhd8ed1ab_1
  - requests-toolbelt=0.10.1=pyhd8ed1ab_0
  - rfc3986=1.5.0=pyhd8ed1ab_0
  - rich=13.2.0=pyhd8ed1ab_1
  - rsa=4.9=pyhd8ed1ab_0
  - send2trash=1.8.0=pyhd8ed1ab_0
  - setproctitle=1.3.2=py310h90acd4f_1
  - setuptools=65.6.3=pyhd8ed1ab_0
  - sip=6.6.2=py310hd4537e4_0
  - six=1.16.0=pyh6c4a22f_0
  - snappy=1.1.9=h225ccf5_2
  - sniffio=1.3.0=pyhd8ed1ab_0
  - soupsieve=2.3.2.post1=pyhd8ed1ab_0
  - sqlalchemy=1.4.46=py310h90acd4f_0
  - sqlalchemy-jsonfield=1.0.1.post0=pyhd8ed1ab_0
  - sqlalchemy-utils=0.39.0=pyhd8ed1ab_0
  - sqlalchemy-utils-arrow=0.39.0=pyhd8ed1ab_0
  - sqlalchemy-utils-babel=0.39.0=pyhd8ed1ab_0
  - sqlalchemy-utils-base=0.39.0=pyhd8ed1ab_0
  - sqlalchemy-utils-color=0.39.0=pyhd8ed1ab_0
  - sqlalchemy-utils-encrypted=0.39.0=pyhd8ed1ab_0
  - sqlalchemy-utils-intervals=0.39.0=pyhd8ed1ab_0
  - sqlalchemy-utils-password=0.39.0=pyhd8ed1ab_0
  - sqlalchemy-utils-pendulum=0.39.0=pyhd8ed1ab_0
  - sqlalchemy-utils-phone=0.39.0=pyhd8ed1ab_0
  - sqlalchemy-utils-timezone=0.39.0=pyhd8ed1ab_0
  - sqlalchemy-utils-url=0.39.0=pyhd8ed1ab_0
  - sqlite=3.40.1=h880c91c_0
  - sqlparse=0.4.3=pyhd8ed1ab_0
  - stack_data=0.2.0=pyhd8ed1ab_0
  - swagger-ui-bundle=0.0.6=py_0
  - tabulate=0.9.0=pyhd8ed1ab_1
  - tenacity=8.1.0=pyhd8ed1ab_0
  - termcolor=2.2.0=pyhd8ed1ab_0
  - terminado=0.17.1=pyhd1c38e8_0
  - text-unidecode=1.3=py_0
  - tinycss2=1.2.1=pyhd8ed1ab_0
  - tk=8.6.12=h5dbffcc_0
  - toml=0.10.2=pyhd8ed1ab_0
  - tomli=2.0.1=pyhd8ed1ab_0
  - tornado=6.2=py310h90acd4f_1
  - traitlets=5.7.1=pyhd8ed1ab_0
  - typing-extensions=4.4.0=hd8ed1ab_0
  - typing_extensions=4.4.0=pyha770c72_0
  - tzdata=2022g=h191b570_0
  - uc-micro-py=1.0.1=pyhd8ed1ab_0
  - unicodecsv=0.14.1=py_1
  - unidecode=1.3.6=pyhd8ed1ab_0
  - urllib3=1.26.14=pyhd8ed1ab_0
  - utf8proc=2.6.1=h9ed2024_0
  - wcwidth=0.2.5=pyh9f0ad1d_2
  - webencodings=0.5.1=py_1
  - websocket-client=0.58.0=py310hecd8cb5_4
  - werkzeug=2.2.2=pyhd8ed1ab_0
  - wheel=0.37.1=pyhd8ed1ab_0
  - widgetsnbextension=3.5.2=py310h2ec42d9_1
  - wrapt=1.14.1=py310h90acd4f_1
  - wtforms=3.0.1=pyhd8ed1ab_0
  - xz=5.2.10=h6c40b1e_1
  - yaml=0.2.5=h0d85af4_2
  - yarl=1.8.2=py310h90acd4f_0
  - zeromq=4.3.4=he49afe7_1
  - zipp=3.11.0=pyhd8ed1ab_0
  - zlib=1.2.13=h8a1eda9_5
  - zstd=1.5.2=hbc0c0cd_6
  - pip:
      - kafka-python==2.0.2
      - py4j==0.10.9.7
      - pyqt5-sip==12.11.0
      - pyspark==3.4.1
      - sodapy==2.2.0
prefix: /Users/eviljimmy/opt/anaconda3/envs/spark
